// import './BasicType/index.ts'
// import './Symbol/index'
// import './Interface/index'
// import './Func/index'
// import './Class/index'
// import './Class/index2'
// import './ENUM/index'
// import './TypeInfer&union/index'
import './AdvancedType/index'